In [65]:
import numpy as np
#The matrix
A = [[5,3,0,0,7,0,0,0,0],
     [8,0,0,1,9,5,0,0,0],
     [0,9,8,0,0,0,0,6,0],
     [8,0,0,0,6,0,0,0,3],
     [4,0,0,8,0,3,0,0,1],
     [7,0,0,0,2,0,0,0,6],
     [0,6,0,0,0,0,2,8,0],
     [0,0,0,4,1,9,0,0,5],
     [0,0,0,0,8,0,0,7,9]]

In [66]:
print(np.matrix(A))

[[5 3 0 0 7 0 0 0 0]
 [8 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [67]:
def posible(x,y,n):
    global A
    # Gia grammi
    for j in range(0,9):
        if A[x][j] == n:
            return False
    for i in range(0,9):
        if A[i][y] == n:
            return False
    xo = (x//3)*3;
    yo = (y//3)*3;
    for i in range(xo,xo+3):
        for j in range (yo,yo+3):
            if A[i][j] == n:
                return False
    return True

posible(0,2,9)

False

In [63]:
for i in range(0,9):
    for j in range(0,9):
        if A[i][j]==0:
            pos = [];
            for n in range(0,9):
                if posible(i,j,n):
                    pos.append(n)
            if len(pos) == 1:
                print('Posible',i,j,':',pos)
                A[i][j] = pos(0)
            print('Posible',i,j,':',pos)

Posible 0 2 : [1, 2, 4, 6]
Posible 0 3 : [2, 6]
Posible 0 5 : [2, 4, 6, 8]
Posible 0 6 : [1, 4, 8]
Posible 0 7 : [1, 2, 4]
Posible 0 8 : [2, 4, 8]
Posible 1 1 : [2, 4, 7]
Posible 1 2 : [2, 4, 6, 7]
Posible 1 6 : [3, 4, 7]
Posible 1 7 : [2, 3, 4]
Posible 1 8 : [2, 4, 7]
Posible 2 0 : [1, 2]
Posible 2 3 : [2, 3]
Posible 2 4 : [3, 4]
Posible 2 5 : [2, 4]
Posible 2 6 : [1, 3, 4, 5, 7]
Posible 2 8 : [2, 4, 7]
Posible 3 1 : [1, 2, 5]
Posible 3 2 : [1, 2, 5]
Posible 3 3 : [5, 7]
Posible 3 5 : [1, 4, 7]
Posible 3 6 : [4, 5, 7]
Posible 3 7 : [2, 4, 5]
Posible 4 1 : [2, 5]
Posible 4 2 : [2, 5, 6]
Posible 4 6 : [5, 7]
Posible 4 7 : [2, 5]
Posible 5 1 : [1, 5]
Posible 5 2 : [1, 3, 5]
Posible 5 5 : [1, 4]
Posible 5 6 : [4, 5, 8]
Posible 5 7 : [4, 5]
Posible 6 0 : [1, 3]
Posible 6 2 : [1, 3, 4, 5, 7]
Posible 6 3 : [3, 5, 7]
Posible 6 4 : [3, 5]
Posible 7 0 : [2, 3]
Posible 7 1 : [2, 7, 8]
Posible 7 2 : [2, 3, 7]
Posible 7 6 : [3, 6]
Posible 8 0 : [1, 2, 3]
Posible 8 1 : [1, 2, 4, 5]
Posible 8 2 : [1

In [68]:
print(np.matrix(A))


[[5 3 0 0 7 0 0 0 0]
 [8 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]
